### ISSUE TITLE
Why time entries have no params?

### ISSUE THREAD

**Issue by EatsLemons** [zanran/node-redmine#13]
Redmines rest api supports additional params, like `limit`, but in lib i see 
`this.request('GET', '/time_entries.json', {}, callback);`
Can `{}` be changed for `params` ?

**Comment by tianxiaxi** [comment]
@EatsLemons, there is not params in https://www.redmine.org/projects/redmine/wiki/Rest_TimeEntries#Listing-time-entries

But I will have a try, if the `params` is available, I would upgrade.

**Comment by tianxiaxi** [comment]
Sorry for fixed late. 

I already commit #2b49d444 and fixed this iss.
