### ISSUE TITLE
No support for accesing Redmine over HTTPS

### ISSUE THREAD

**Issue by seppestas** [zanran/node-redmine#2]
Since this library uses [Node's HTTP library](https://nodejs.org/api/http.html) it does not support accessing the Redmine API over HTTPS.

Since sensitive data is sent to the API (i.e API keys or confidential data) it makes a lot of sense to use HTTPS.

**Comment by tianxiaxi** [comment]
@seppestas could you give me more details, I do test on HTTPS, it works for me.

Please see the following test code :
```javascript
var Redmine       = require('node-redmine');
var url           = require('url');

var urlInfo = url.parse('https://example.com');
var config = {
  apiKey: 'token here',
  format: 'json'
};
var redmine = new Redmine(urlInfo.hostname, config, urlInfo.port);

// get issue by id
var params = {include: 'attachments,journals,watchers'};
var issue_id = 100;
redmine.get_issue_by_id(issue_id, params, function(err, data) {
  if (err) throw err;

  console.log(data.issue);
});
```

**Comment by seppestas** [comment]
@tianxiaxi this will still result in HTTP requests to the Redmine API.

The only way to know an endpoint should use HTTP or HTTPS using `url` is by using the `urlInfo .protocol` property.  In your example, `urlInfo.host` will just result in `example.com` and `urlInfo.port` will result in `null`, causing node-redmine to still do a (valid) HTTP request. Also, node's http module does not support the HTTPS protocol, for this the [http](https://nodejs.org/api/https.html) module should be used.

IMO there are to options:
- Use a helper library, e.g [request](https://github.com/request/request), that is able to figure out the protocol to be used for the endpoint instead of the built in `http` library.
- Add something like a `protocol` option to the `Redmine` constructor that allows node-redmine to chose between `http` and `https`, e.g like in [request](https://github.com/request/request/blob/master/request.js#L457)

What is your preference? I might send a PR when I find some time.

**Comment by tianxiaxi** [comment]
@seppestas As you just mentioned, those two options are both available. You could choose any one by your options.

It would be perfect if you could do a pull request, and work together.
