### ISSUE TITLE
Need to specify protocol in hostname

### ISSUE THREAD

**Issue by indriApollo** [zanran/node-redmine#21]
I noticed that I have to specify the protocol in the hostname like `http://redmine.example.com` otherwise `request` (tested with v2.81.0) throws the following error : `Error: Invalid URI "redmine.example.com/projects.json"` .

Shouldn't the examples be updated ?

**Comment by tianxiaxi** [comment]
Sorry for reply late.
I already updated the usage example in https://github.com/zanran/node-redmine#usage
