### ISSUE TITLE
update npm release

### ISSUE THREAD

**Issue by grptx** [zanran/node-redmine#28]
Hi
can you update the version published in [npmjs.com](https://www.npmjs.com/package/node-redmine) to last commit (so we have the upload fix)?

thx

**Comment by vKarter** [comment]
@tianxiaxi are you alive after COVID-19 ?

**Comment by tianxiaxi** [comment]
@grptx @vKarter Sorry for not logged on github for years. The new version v0.2.2 has published for minutes.
