### ISSUE TITLE
Format always gets overwritten to json

### ISSUE THREAD

**Issue by seppestas** [zanran/node-redmine#4]
Even though it's possible to pass a 'format' in the config parameter, [this library always overwrites the format to json](https://github.com/zanran/node-redmine/blob/master/lib/redmine.js#L45). This does not make a lot of sense IMO.

Either this library shouldn't give the option for the user to specify the format or it should use the specified format.

**Comment by tianxiaxi** [comment]
Redmine REST API supports `json` and `xml` formats. Although `node-redmine` only support `json` currently, we are planing to support `xml` in the future.

**Comment by seppestas** [comment]
But... Why?

**Comment by tianxiaxi** [comment]
I want `node-redmine` to be a 100% feature supported for Redmine REST API.
And may some app which use `node-redmine` only support `xml` format.

**Comment by seppestas** [comment]
This is a JS Redmine library, and it has "node" as part of it's name. I'm fairly certain all versions of Node and pretty much every browser still in use today support JSON deserialization.
Using JSON object is a lot more convenient than using JS's built in XML DOM Tree parsing functions, so I don't see why people would ever opt to use XML over JSON in JS for the type of data the Redmine API exposes.

IMO implementing and supporting a feature just because people **might** use it or just to be feature complete is a waste of time, there is plenty of useful stuff to do in life. If people want this library to support XML they could always open an issue and the feature can be implemented when you know it is actually going to be used. Having features sit around without being used only results in code rot, which is kinda of what happend to the format option...

**Comment by tianxiaxi** [comment]
Thank you for your suggest. You are right, using `JSON` is more convenient than `XML` in node. I will merge your request as soon as possible.
