### ISSUE TITLE
problem in 0.1.3

### ISSUE THREAD

**Issue by sephiroth945** [zanran/node-redmine#7]
I try to write a batch user, issues add script, but I found some problem in 0.1.3. I try the example code from redmine-user.js, in ver 0.1.2, everythind works OK, but throw error in ver 0.1.3.

my code from example/redmine-user.js(works fine in ver 0.1.2)

> var dump_user = function(user) {
>   console.log('Dumping user:');
>   for (var item in user) {
>     console.log('  ' + item + ': ' + JSON.stringify(user[item]));
>   }
> };
> redmine.current_user({include: "memberships,groups"}, function(err, data) {
>   if (err) throw err;
>   dump_user(data.user);
> });

error message in ver 0.1.3

> E:\node-mis_redmine\create_issue.js:30
>   if (err) throw err;
>            ^
> 
> Error: Invalid URI "134.134.30.52/users/current.json"
>     at Request.init (E:\WebRoot\NodeJS\node-mis_redmine\node_modules\request\request.js:274:31)
>     at new Request (E:\WebRoot\NodeJS\node-mis_redmine\node_modules\request\request.js:128:8)
>     at request (E:\WebRoot\NodeJS\node-mis_redmine\node_modules\request\index.js:54:10)
>     at Redmine._request (E:\WebRoot\NodeJS\node-mis_redmine\node_modules\request\index.js:101:12)
>     at Redmine.request (E:\WebRoot\NodeJS\node-mis_redmine\node_modules\node-redmine\lib\redmine.js:115:18)
>     at Redmine.current_user (E:\WebRoot\NodeJS\node-mis_redmine\node_modules\node-redmine\lib\redmine.js:261:7)
>     at Object.<anonymous> (E:\WebRoot\NodeJS\node-mis_redmine\create_issue.js:27:9)
>     at Module._compile (module.js:573:32)
>     at Object.Module._extensions..js (module.js:582:10)
>     at Module.load (module.js:490:32)
>     at tryModuleLoad (module.js:449:12)
>     at Function.Module._load (module.js:441:3)
>     at Module.runMain (module.js:607:10)
>     at run (bootstrap_node.js:382:7)
>     at startup (bootstrap_node.js:137:9)
>     at bootstrap_node.js:497:3

**Comment by tianxiaxi** [comment]
If the problem occurs again, please reopen it.
