### ISSUE TITLE
Unable to set port in 0.1.3

### ISSUE THREAD

**Issue by tommarshall** [zanran/node-redmine#8]
The `port` parameter is ignored in the latest 0.1.3 version.

It looks to have been broken in commit https://github.com/zanran/node-redmine/pull/5/commits/adbb7f61048675b88fa9d6c3fff91276a4e747d6 where `http` was replaced with `request`.

[There's an attempt made to set the port](https://github.com/zanran/node-redmine/blob/adbb7f61048675b88fa9d6c3fff91276a4e747d6/lib/redmine.js#L36), but setting the port on a `url` object like this does not update the `href` property.

Reduced test case:

```js
var URL = require('url');
var url = URL.parse('example.com');
console.log(url.href); // example.com
url.port = 8080;
console.log(url.href); // example.com
```

**Comment by tianxiaxi** [comment]
this issue duplicate with #7 , I will fix it as soon as possible.

**Comment by tianxiaxi** [comment]
Now there are two method passing`port`:
+ Assign port at the end of host string, e.g. `http://www.example.com:6789`
+ Pass the `port` argument, e.g: 
```node
var redmine = new Redmine('http://www.example.com', config, 6789);
```
